-- DAY 1: SQL BASICS
-- AUTHOR: SHRUTI MANKAR
-- GOAL: LEARN BASIC SQL QUERIES AND FILTERING
/*
TOPICS COVERED
1. SELECT statement
2. WHERE clause
3. Filtering conditions
4. AND/OR conditions
*/

-- Table Structure:
-- Assumed: EMPLOYEES(ID, NAME, DEPT, SALARY, CITY)

-- SELECT ALL COLUMNS
SELECT * FROM EMPLOYEES;

-- SELECT SPECIFIC COLUMNS
SELECT ID,NAME FROM EMPLOYEES;

-- FILTER RECORDS USING WHERE
SELECT * FROM EMPLOYEES 
WHERE DEPT = 'IT';

-- FILTER SALARY GREATER THAN 30K
SELECT * FROM EMPLOYEES
WHERE SALARY > 30000;

-- FILTER BY CITY
SELECT * FROM EMPLOYEES
WHERE CITY = 'MUMBAI';

-- MULTIPLE CONDITIONS USING AND
SELECT * FROM EMPLOYEES
WHERE DEPT = 'IT'
AND SALARY = 30000;

-- MULTIPLE VALUES USING IN
SELECT * FROM EMPLOYEES
WHERE DEPT IN ('IT','HR')
AND SALARY = 30000;

-- USING OR CONDITION
SELECT * FROM EMPLOYEES
WHERE CITY = 'MUMBAI'
OR CITY = 'PUNE';

-- PRACTICE QUESTIONS
-- Q1: GET ALL EMPLOYEES FROM HR DEPT
SELECT * FROM EMPLOYEES 
WHERE DEPT = 'HR';

-- Q2: GET ALL EMPLOYEES WITH SALARY LESS THAN 25K
SELECT * FROM EMPLOYEES
WHERE SALARY < 25000;

-- Q3: GET EMPLOYEES FROM MUMBAI WITH SALARY > 30K
SELECT * FROM EMPLOYEES
WHERE CITY = 'MUMBAI'
AND SALARY > 30000;

-- Q4: GET EMPLOYEES NOT FROM PUNE
SELECT * FROM EMPLOYEES
WHERE CITY NOT IN ('PUNE');

-- Q5: GET EMPLOYEES FROM IT OR FINANCE DEPT
SELECT * FROM EMPLOYEES 
WHERE DEPT = 'IT'
OR DEPT = 'FINANCE';

-- LEARNING NOTES
/*
SELECT: TO FETCH DATA
WHERE: TO FILTER DATA/RECORDS
OPERATORS:
= (EQUAL)
> GREATER THAN
< LESS THAN
IN: MULTIPLE VALUES
AND: BOTH CONDITIONS MUST BE TRUE
OR: ANY CONDITION TRUE
*/






