-- DAY 2: GROUP BY, HAVING & AGRREGATE FUNCTIONS
-- AUTHOR: SHRUTI MANKAR
-- GOAL: LEARN GROUP BY & AGRREGATE FUNCTIONS
/*
TOPICS COVERED
1. COUNT()
2. AVG()
3. SUM()
4. MIN()/MAX()
5. GROUP BY
6. HAVING
*/

-- Table Structure:
-- Assumed: EMPLOYEES(ID, NAME, DEPT, SALARY, CITY)

-- AGGREGATE FUNCTIONS

-- COUNT TOTAL EMPLOYEES
SELECT COUNT(*) FROM EMPLOYEES;

-- COUNT EMPLOYEES WITH NAMES
SELECT COUNT(NAME) FROM EMPLOYEES;

-- AVERAGE SALARY
SELECT AVG(SALARY) FROM EMPLOYEES;

-- TOTAL SALARY
SELECT SUM(SALARY) FROM EMPLOYEES;

-- MINIMUM SALARY
SELECT MIN(SALARY) FROM EMPLOYEES;

-- MAXIMUM SALARY
SELECT MAX(SALARY) FROM EMPLOYEES;

-- GROUP BY

-- COUNT EMPLOYEES PER DEPT
SELECT DEPT, COUNT(*) FROM EMPLOYEES
GROUP BY DEPT;

-- AVERAGE SALARY PER DEPT
SELECT DEPT, AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPT;

-- TOTAL SALARY PER DEPT
SELECT DEPT, SUM(SALARY) FROM EMPLOYEES
GROUP BY DEPT;

-- MIN SALARY PER DEPT
SELECT DEPT, MIN(SALARY) FROM EMPLOYEES
GROUP BY DEPT;

-- MAX SALARY PER DEPT
SELECT DEPT, MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPT;

-- HAVING (FILTERED ON GROUP DATA)

-- DEPT WITH AVG SALARY > 40000
SELECT DEPT, AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPT
HAVING AVG(SALARY) > 40000;

-- DEPT WITH MORE THAN 2 EMPLOYEES
SELECT DEPT, COUNT(*) FROM EMPLOYEES
GROUP BY DEPT
HAVING COUNT(*) > 2;

-- ORDER BY WITH GROUP BY
-- DEPT WITH HIGHEST EMPLOYEE COUNT
SELECT DEPT, COUNT(*) AS EMP_CNT FROM EMPLOYEES
GROUP BY DEPT
ORDER BY EMP_CNT DESC
LIMIT 1;

-- PRACTICE QUESTIONS
-- Q1: FIND TOTAL SALARY PER CITY
SELECT CITY, SUM(SALARY) FROM EMPLOYEES 
GROUP BY CITY;

-- Q2: FIND AVG SALARY PER CITY
SELECT CITY, AVG(SALARY) FROM EMPLOYEES 
GROUP BY CITY;

-- Q3: FIND DEPT WITH HIGHEST AVG SALARY
SELECT DEPT, AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
GROUP BY DEPT
ORDER BY AVG_SAL DESC
LIMIT 1;

-- Q4: FIND DEPT WITH TOTAL SALARY GREATER THAN 10000
SELECT DEPT, SUM(SALARY) AS TOT_SAL FROM EMPLOYEES
WHERE TOT_SAL > 10000;

-- Q5: COUNT EMPLOYEES IN EACH CITY
SELECT CITY, COUNT(*) FROM EMPLOYEES
GROUP BY CITY;

-- LEARNING NOTES
/*
GROUP BY: Groups rows with same value into summary rows

AGGREGATE FUNCTIONS:
COUNT(): number of rows
AVG(): Average values
SUM(): total value
MIN(): minimum value
MAX(): maximum value

HAVING V/S WHERE
WHERE: filters the data before grouping
HAVING: filters after grouping

Best Practice:
Always include GROUP BY when using aggregates with columns
Use meaningful alias (AS)
*/







