-- DAY 3: JOINS
-- AUTHOR: SHRUTI MANKAR
-- GOAL: Understand how to combine data from multiple tables
/*
TOPICS COVERED
1. INNER JOIN
2. LEFT JOIN
3. RIGHT JOIN
4. FULL JOIN (concept)
*/

-- Table Structure:
-- Assumed: EMPLOYEES(ID, NAME, DEPT_ID, SALARY, CITY)
-- Assumed: DEPARTMENTS(DEPT_ID, DEPT_NAME)

-- 1. INNER JOIN
-- GET EMPLOYEE NAME, SALARY AND DEPT_NAME
SELECT E.NAME, E.SALARY, D.DEPT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID;

-- LEFT JOIN
-- GET ALL EMPLOYEES AND THEIR DEPTS
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID;

-- RIGHT JOIN
-- GET ALL DEPT & EMPLOYEES (IF EXISTS)
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID;

-- FULL JOIN
-- NOT SUPPORTED IN MYSQL DIRECTLY
-- COMBINE LEFT+RIGHT JOIN

-- EMPLOYEES WITHOUT DEPT
SELECT E.NAME FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID
WHERE D.DEPT_ID IS NULL;

-- DEPT WITHOUT EMPLOYEES
SELECT D.DEPT_NAME FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPT_ID, E.DEPT_ID
WHERE E.DEPT_ID IS NULL;

-- PRACTICE QUESTIONS
-- Q1: GET EMPLOYEE WITH DEPT NAME
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID;

-- Q2: GET EMPLOYEE WITH DEPT NAME EVEN IF THEY DON'T HAVE
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID;

-- Q3: GET EMPLOYEES WHO DOESN'T BELONG TO ANY DEPT
SELECT E.NAME FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID
WHERE D.DEPT_ID IS NULL;

-- Q4: GET DEPT WITHOUT ANY EMPLOYEES
SELECT D.DEPT_NAME FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPT_ID, E.DEPT_ID
WHERE E.DEPT_ID IS NULL;

-- Q4: GET EMPLOYEES COUNT PER DEPT WITH JOINS
SELECT D.DEPT_NAME, COUNT(*) FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPT_ID, D.DEPT_ID
GROUP BY DEPT;

-- LEARNING NOTES
/*
JOIN: used to combine data from multiple tables.
INNER JOIN: returns only matching data
LEFT JOIN: returns all data from left table
RIGHT JOIN: returns all data from right table
FULL JOINS: returns all records from both tables

Best Practice: 
Always use table aliases (eg. E, D)
Always define proper join condition (ON)
*/
