-- DAY 4: SUBQUERIES
-- AUTHOR: SHRUTI MANKAR
-- GOAL: LEARN HOW TO USE QUERIES INSIDE QUERIES
/*
TOPICS COVERED
1. SUBQUERY IN WHERE
2. SUBQUERY WITH AGGREGATE FUNCTIONS
3. CORRELATED SUBQUERY (BASIC IDEA)
*/

-- Table Structure:
-- Assumed: EMPLOYEES(ID, NAME, DEPT, SALARY, CITY)
-- Assumed: DEPARTMENTS(DEPT_ID, DEPT_NAME)

-- 1. SUBQUERY IN WHERE
-- EMPLOYEE EARNING MORE THAN AVERAGE SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY > 
	(SELECT AVG(SALARY) FROM EMPLOYEES);

-- 2. SUBQUERY WITH MAX
-- FIND SECOND HIGHEST SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY < 
	(SELECT MAX(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC
LIMIT 1;

-- 3. SUBQUERY WITH GROUP BY + HAVING
-- DEPARTMENT WITH AVG SALARY > 40000
SELECT DEPT, AVG(SALARY) FROM EMPLOYEES 
GROUP BY DEPT_ID
HAVING AVG(SALARY) > 40000
	
-- 4. CORRELATED SUBQUERY (CONCEPT)
-- EMPLOYEE EARNING MORE THAN THEIR DEPT AVG
SELECT * FROM EMPLOYEES E
WHERE SALARY > 
	(SELECT AVG(SALARY) FROM EMPLOYEES
	WHERE DEPT_ID = E.DEPT_ID);

-- PRACTICE QUESTIONS
-- Q1: EMPLOYEES EARNING LESS THAN AVG SALARY
SELECT * FROM EMPLOYEES 
WHERE SALARY < 
	(SELECT AVG(SALARY) FROM EMPLOYEES);

-- Q2: HIGHEST SALARY IN EACH DEPT USING SUBQUERY
SELECT * FROM EMPLOYEES E
WHERE SALARY = 
	(SELECT MAX(SALARY) FROM EMPLOYEES
	WHERE DEPT_ID = E.DEPT_ID)

-- Q3: EMPLOYEES EARNING SAME SALARY AS MAX SALARY
SELECT * FROM EMPLOYEES 
WHERE SALARY =
	(SELECT MAX(SALARY) FROM EMPLOYEES);

-- Q4: DEPT WHERE AVG SALARY < 30000
SELECT DEPT_ID FROM EMPLOYEES E
GROUP BY DEPT_ID
HAVING ACG(SALARY) < 30000;

-- Q5: EMPLOYEES EARNING MORE THAN DEPT AVG
SELECT * FROM EMPLOYEES E
WHERE SALARY >
	(SELECT AVG(SALARY) FROM EMPLOYEES
	WHERE DEPT_ID = E.DEPT_ID)

-- LEARNING NOTES
/*
SUBQUERY: query inside query

Types: 
Single value
Multiple vlaue
Correlated

Key Idea: Inner query runs first and out query uses the result of inner query

Best Practice
- Use subqueries for dynamic filtering
- Avoid overusing the JOIN can be simpler
*/
